### ISSUE TITLE
is rolesAllowed working ?

### ISSUE THREAD

**Issue by arvind-das** [bobbywarner/grails3-oauth2-api#4]
I do have almost same setup, not with oauth2 but basic session based. RolesAllowed annotation simple does not work for me. Any guesses ?

**Comment by bobbywarner** [comment]
Just confirming you have this line in your project `@EnableGlobalMethodSecurity(jsr250Enabled = true)`?  Please let me know.

**Comment by arvind-das** [comment]
No, I did not make jsr250Enabled, Will try out with that and let you know

**Comment by arvind-das** [comment]
I am getting this : 

Exception in thread "main"                                                                                                             java.lang.IllegalArgumentException: Class name [org.grails.spring.aop.autoproxy.GroovyAwareAspectJAwareAdvisorAutoProxyCreator] is not a known auto-proxy creator class
    at org.springframework.aop.config.AopConfigUtils.findPriorityForClass(AopConfigUtils.java:140)
    at org.springframework.aop.config.AopConfigUtils.registerOrEscalateApcAsRequired(AopConfigUtils.java:113)
    at org.springframework.aop.config.AopConfigUtils.registerAutoProxyCreatorIfNecessary(AopConfigUtils.java:74)
    at org.springframework.aop.config.AopConfigUtils.registerAutoProxyCreatorIfNecessary(AopConfigUtils.java:70)
    at org.springframework.context.annotation.AutoProxyRegistrar.registerBeanDefinitions(AutoProxyRegistrar.java:69)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:353)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:151)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:124)

**Comment by bobbywarner** [comment]
@arvind-das Are you still facing this issue?  I've not been able to replicate it.  Please let me know.
